spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo1234@localhost:27017/mongo
      database: mongo
  application:
    name: m-auth

server:
  port: 8081

token:
  expired:
    base: 86400000
    refresh: 87000000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka